# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: backend-gpt ci/cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Create env file from GitHub Secrets
        run: |
          cat > .env <<EOF
          PORT=8080
          NGC_API_KEY=${{ secrets.NGC_API_KEY }}
          MONGODB_URL=${{ secrets.MONGODB_URL }}
          EOF

      - name: Restart app with PM2
        run: |
          pm2 stop backend-gpt || true
          pm2 delete backend-gpt || true
          pm2 start ecosystem.config.js
          pm2 save
